language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0"
  - TRAVIS_BUILD_DIR="/home/odoo/build/ygol/odoo_asterisk/odoo-addons"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install humanize git+https://github.com/litnimax/PyAjam.git requests
  - pip install gevent git+https://github.com/digium/swagger-py.git ari odoorpc py-Asterisk requests setproctitle

before_script:
  - python ${HOME}/../services/stasis_app.py
  - python ${HOME}/../services/ami_broker.py

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
