version: '3.2'
services:
  db:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - data-db:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      default:
        ipv4_address: ${DB_IP}
    extra_hosts:
      - asterisk:${BRIDGE_IP}

  odoo:
    build: ./odoo
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=asterisk
      - DB_HOST=${DB_IP:-db}
      - ADMIN_PASSWD=admin-change-me
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=base
      - LOG_HANDLER=:WARN
      - MARABUNTA_FORCE_VERSION=${MARABUNTA_FORCE_VERSION}
    ports:
      - 8069
      - 8072
    networks:
      default:
        ipv4_address: ${ODOO_IP}
    extra_hosts:
      - asterisk:${BRIDGE_IP}

  #odoo_mqtt_broker:
  #  build: ./odoo_mqtt_broker
  #  restart: unless-stopped
  #  depends_on:
  #    - odoo
  #    - broker
  #  environment:
  #    - MQTT_HOST=${BROKER_IP}
  #    - ODOO_IP=${ODOO_IP:-odoo}
  #    - ODOO_DB=asterisk
  #    - ODOO_USER=admin
  #    - ODOO_PASSWORD=admin

  nginx:
    image: camptocamp/odoo-nginx:9.0-1.1.0
    depends_on:
      - odoo
    ports:
      - 80
    networks:
      default:
        ipv4_address: ${NGINX_IP}
    extra_hosts:
        - odoo:${ODOO_IP}

  asterisk:
    build:  asterisk
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - ODOO_IP=${ODOO_IP:-odoo}
      - ODOO_DB=asterisk
      - ODOO_USER=admin
      - ODOO_PASSWORD=admin
      - HTTP_ENABLED=yes
      - MANAGER_ENABLED=yes
      - MANAGER_WEB_ENABLED=yes
      - MANAGER_LOGIN=odoo
      - MANAGER_PASSWORD=odoo
      - MANAGER_PORT=5038
      - MANAGER_LISTEN_ADDRESS=127.0.0.1
      - HTTP_LISTEN_ADDRESS=127.0.0.1
      - HTTP_PORT=8088
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=asterisk
      - DB_HOST=${DB_IP:-db}
      - ASTERISK_BINARY=/usr/sbin/asterisk
      - CONSOLE_LISTEN_ADDRESS=0.0.0.0
      - CONSOLE_LISTEN_PORT=8010
    #network_mode: host
    networks:
      default:
        ipv4_address: ${ASTERISK_IP}
    ports:
      - 5038
      - 5060/udp
      - 8010
      - 8088
    extra_hosts:
      - db:${DB_IP}
      - odoo:${ODOO_IP}
      - broker:${BROKER_IP}

  broker:
    build: broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      default:
        ipv4_address: ${BROKER_IP}

volumes:
  data-odoo:
  data-db:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
